// ============================================================================
// Demo fixtures for the new domain entities introduced in this pass:
// repositories, code & CI/CD issues, SCA findings, integrations, attack
// paths, and remediation scenarios. Legacy fixtures (risks/findings/assets/
// compliance) remain in src/utils/mock.ts and are re-exported where useful.
// ============================================================================

import type {
  Repository,
  CodeIssue,
  SCAFinding,
  Integration,
  AttackPath,
  RemediationScenario,
  TimelineEvent,
  PipelineStage,
} from '../types';

export const REPOSITORIES: Repository[] = [
  {
    id: 'repo-ml-kit',
    name: 'codesmiths/ml-kit',
    provider: 'github',
    defaultBranch: 'main',
    securityScore: 62,
    lastScan: '2026-08-24T09:45:00Z',
    criticalIssues: 4,
    openVulnerabilities: 11,
    secrets: 2,
    dependencies: 184,
    iacIssues: 3,
    owners: [{ name: 'Priya Nair', initials: 'PN', team: 'ML Platform' }],
    issues: { critical: 4, high: 7, medium: 12, low: 20 },
    language: 'Python',
    framework: 'FastAPI',
  },
  {
    id: 'repo-payments-service',
    name: 'codesmiths/payments-service',
    provider: 'gitlab',
    defaultBranch: 'master',
    securityScore: 48,
    lastScan: '2026-08-24T08:10:00Z',
    criticalIssues: 6,
    openVulnerabilities: 18,
    secrets: 1,
    dependencies: 231,
    iacIssues: 5,
    owners: [{ name: 'Arjun Mehta', initials: 'AM', team: 'Payments' }],
    issues: { critical: 6, high: 9, medium: 14, low: 22 },
    language: 'Java',
    framework: 'Spring Framework',
  },
  {
    id: 'repo-auth-service',
    name: 'codesmiths/auth-service',
    provider: 'github',
    defaultBranch: 'main',
    securityScore: 55,
    lastScan: '2026-08-23T22:05:00Z',
    criticalIssues: 3,
    openVulnerabilities: 9,
    secrets: 1,
    dependencies: 96,
    iacIssues: 2,
    owners: [{ name: 'Sara Kapoor', initials: 'SK', team: 'Identity' }],
    issues: { critical: 3, high: 6, medium: 10, low: 15 },
    language: 'Node.js',
    framework: 'Express',
  },
  {
    id: 'repo-frontend-web',
    name: 'codesmiths/frontend-web',
    provider: 'github',
    defaultBranch: 'main',
    securityScore: 79,
    lastScan: '2026-08-24T06:30:00Z',
    criticalIssues: 1,
    openVulnerabilities: 5,
    secrets: 0,
    dependencies: 412,
    iacIssues: 0,
    owners: [{ name: 'Dev Sharma', initials: 'DS', team: 'Web Platform' }],
    issues: { critical: 1, high: 3, medium: 8, low: 18 },
    language: 'TypeScript',
    framework: 'React',
  },
  {
    id: 'repo-infra-production',
    name: 'codesmiths/infra-production',
    provider: 'gitlab',
    defaultBranch: 'main',
    securityScore: 41,
    lastScan: '2026-08-24T05:15:00Z',
    criticalIssues: 6,
    openVulnerabilities: 14,
    secrets: 3,
    dependencies: 58,
    iacIssues: 27,
    owners: [{ name: 'Rahul Verma', initials: 'RV', team: 'Platform Infra' }],
    issues: { critical: 6, high: 9, medium: 16, low: 26 },
    language: 'HCL',
    framework: 'Terraform',
  },
];

export const CODE_ISSUES: CodeIssue[] = [
  {
    id: 'CI-001',
    rule: 'Publicly exposed code repository with sensitive secrets',
    issues: 4,
    risks: ['public', 'secret'],
    severity: 'CRITICAL',
    repository: 'codesmiths/infra-production',
    branch: 'main',
    framework: 'Terraform',
    status: 'OPEN',
    category: 'secrets',
  },
  {
    id: 'CI-002',
    rule: 'Version control system repository with exposed admin credentials',
    issues: 4,
    risks: ['secret', 'privileged'],
    severity: 'CRITICAL',
    repository: 'codesmiths/payments-service',
    branch: 'master',
    framework: 'Spring',
    status: 'OPEN',
    category: 'secrets',
  },
  {
    id: 'CI-003',
    rule: 'Publicly exposed code repository with hardcoded cloud keys',
    issues: 4,
    risks: ['public', 'cloud'],
    severity: 'CRITICAL',
    repository: 'codesmiths/ml-kit',
    branch: 'main',
    framework: 'FastAPI',
    status: 'OPEN',
    category: 'secrets',
  },
  {
    id: 'CI-004',
    rule: 'Publicly exposed version control system with weak branch protection',
    issues: 2,
    risks: ['public', 'branch'],
    severity: 'CRITICAL',
    repository: 'codesmiths/auth-service',
    branch: 'main',
    framework: 'Express',
    status: 'IN_PROGRESS',
    category: 'posture',
  },
  {
    id: 'CI-005',
    rule: 'Publicly exposed repository with branch protection disabled',
    issues: 2,
    risks: ['public'],
    severity: 'CRITICAL',
    repository: 'codesmiths/frontend-web',
    branch: 'main',
    framework: 'React',
    status: 'OPEN',
    category: 'posture',
  },
  {
    id: 'CI-006',
    rule: 'Container registry (ECR) repository without image scanning enabled',
    issues: 3,
    risks: ['cloud', 'privileged'],
    severity: 'HIGH',
    repository: 'codesmiths/infra-production',
    branch: 'main',
    framework: 'Docker',
    status: 'OPEN',
    category: 'iac',
  },
  {
    id: 'CI-007',
    rule: 'Insecure Terraform module allows unrestricted security group ingress',
    issues: 6,
    risks: ['network'],
    severity: 'HIGH',
    repository: 'codesmiths/infra-production',
    branch: 'main',
    framework: 'Terraform',
    status: 'OPEN',
    category: 'iac',
  },
  {
    id: 'CI-008',
    rule: 'Dependency with known critical CVE reachable from entrypoint',
    issues: 3,
    risks: ['cve'],
    severity: 'CRITICAL',
    repository: 'codesmiths/payments-service',
    branch: 'master',
    framework: 'Spring',
    status: 'OPEN',
    category: 'sca',
  },
];

export const SCA_FINDINGS: SCAFinding[] = [
  {
    id: 'SCA-001',
    cve: 'CVE-2023-0215',
    severity: 'CRITICAL',
    component: 'cryptography',
    version: '3.3.2',
    fixedVersion: '39.0.1',
    reachable: true,
    exploitAvailable: true,
    status: 'OPEN',
    repository: 'codesmiths/payments-service',
  },
  {
    id: 'SCA-002',
    cve: 'CVE-2023-4076',
    severity: 'CRITICAL',
    component: 'org.springframework',
    version: '2.1.1',
    fixedVersion: '2.7.14',
    reachable: true,
    exploitAvailable: false,
    status: 'OPEN',
    repository: 'codesmiths/payments-service',
  },
  {
    id: 'SCA-003',
    cve: 'CVE-2021-1974',
    severity: 'HIGH',
    component: 'org.springframework',
    version: '6.2.3',
    fixedVersion: '6.2.9',
    reachable: false,
    exploitAvailable: false,
    status: 'OPEN',
    repository: 'codesmiths/payments-service',
  },
  {
    id: 'SCA-004',
    cve: 'CVE-2024-21887',
    severity: 'CRITICAL',
    component: 'ivanti-connect',
    version: '9.1.1',
    fixedVersion: '9.1.5',
    reachable: true,
    exploitAvailable: true,
    status: 'OPEN',
    repository: 'codesmiths/auth-service',
  },
  {
    id: 'SCA-005',
    cve: 'CVE-2024-3400',
    severity: 'CRITICAL',
    component: 'palo-alto-panos',
    version: '10.2.1',
    fixedVersion: '10.2.9',
    reachable: true,
    exploitAvailable: true,
    status: 'IN_PROGRESS',
    repository: 'codesmiths/infra-production',
  },
  {
    id: 'SCA-006',
    cve: 'CVE-2022-42889',
    severity: 'HIGH',
    component: 'commons-text',
    version: '1.9',
    fixedVersion: '1.10.0',
    reachable: false,
    exploitAvailable: false,
    status: 'FIXED',
    repository: 'codesmiths/ml-kit',
  },
];

export const INTEGRATIONS: Integration[] = [
  { id: 'int-github', key: 'github', name: 'GitHub', category: 'code', status: 'connected', lastSync: '2026-08-24T09:40:00Z', itemsIngested: 5, errors: 0, description: 'Source code, pull requests, and repository security posture.' },
  { id: 'int-gitlab', key: 'gitlab', name: 'GitLab', category: 'code', status: 'connected', lastSync: '2026-08-24T08:10:00Z', itemsIngested: 2, errors: 0, description: 'CI/CD pipelines and repository scanning.' },
  { id: 'int-aws', key: 'aws', name: 'Amazon Web Services', category: 'cloud', status: 'connected', lastSync: '2026-08-24T07:55:00Z', itemsIngested: 312, errors: 0, description: 'Cloud resource inventory and configuration posture (CSPM).' },
  { id: 'int-azure', key: 'azure', name: 'Microsoft Azure', category: 'cloud', status: 'disconnected', itemsIngested: 0, errors: 0, description: 'Cloud resource inventory for Azure subscriptions.' },
  { id: 'int-gcp', key: 'gcp', name: 'Google Cloud', category: 'cloud', status: 'disconnected', itemsIngested: 0, errors: 0, description: 'Cloud resource inventory for GCP projects.' },
  { id: 'int-slack', key: 'slack', name: 'Slack', category: 'collaboration', status: 'connected', lastSync: '2026-08-24T09:00:00Z', itemsIngested: 48, errors: 0, description: 'Send alerts and remediation requests to security channels.' },
  { id: 'int-jira', key: 'jira', name: 'Jira', category: 'ticketing', status: 'connected', lastSync: '2026-08-23T18:20:00Z', itemsIngested: 27, errors: 1, description: 'Create and track remediation tickets automatically.' },
  { id: 'int-siem', key: 'siem', name: 'SIEM', category: 'siem', status: 'disconnected', itemsIngested: 0, errors: 0, description: 'Security event correlation and log analytics.' },
  { id: 'int-edr', key: 'edr', name: 'EDR', category: 'edr', status: 'disconnected', itemsIngested: 0, errors: 0, description: 'Endpoint detection and response telemetry.' },
  { id: 'int-xdr', key: 'xdr', name: 'XDR — CrowdStrike Falcon', category: 'edr', status: 'connected', lastSync: '2026-08-24T09:20:00Z', itemsIngested: 2, errors: 0, description: 'Extended detection and response across endpoints and identities.' },
  { id: 'int-bugbounty', key: 'bugbounty', name: 'Bug Bounty — HackerOne', category: 'bug_bounty', status: 'connected', lastSync: '2026-08-24T09:10:00Z', itemsIngested: 3, errors: 0, description: 'Crowd-sourced vulnerability disclosure program.' },
  { id: 'int-iam', key: 'iam', name: 'IAM — Okta', category: 'identity', status: 'connected', lastSync: '2026-08-24T09:05:00Z', itemsIngested: 2, errors: 0, description: 'Identity posture, MFA coverage, and privileged access review.' },
  { id: 'int-sast', key: 'sast', name: 'SAST Scanner', category: 'sast', status: 'connected', lastSync: '2026-08-24T06:45:00Z', itemsIngested: 63, errors: 0, description: 'Static application security testing across all repositories.' },
  { id: 'int-sca', key: 'sca', name: 'SCA Scanner', category: 'sca', status: 'connected', lastSync: '2026-08-24T06:45:00Z', itemsIngested: 231, errors: 0, description: 'Software composition analysis and SBOM generation.' },
];

export const ATTACK_PATHS: AttackPath[] = [
  {
    id: 'ap-auth-api',
    title: 'Internet → Auth API → IAM Role → Payment Database → Customer Data',
    riskCaseId: 'A003',
    severity: 'CRITICAL',
    nodes: [
      { id: 'internet', label: 'Internet', type: 'internet', x: 60, y: 160 },
      { id: 'public-api', label: 'Public API', type: 'api', severity: 'HIGH', x: 220, y: 80, environment: 'production' },
      { id: 'auth-api', label: 'Authentication API', type: 'api', severity: 'CRITICAL', x: 220, y: 240, environment: 'production', owner: 'Engineering', description: 'Internet-facing API with a validated bug bounty auth-bypass finding and 58% MFA coverage.' },
      { id: 'iam-role', label: 'IAM Role', type: 'identity', severity: 'HIGH', x: 400, y: 160, environment: 'production', owner: 'Identity Team', description: 'Over-privileged service role assumable by Authentication API on failure path.' },
      { id: 'payment-service', label: 'Payment Service', type: 'compute', severity: 'HIGH', x: 580, y: 80, environment: 'production', owner: 'Payments' },
      { id: 'payment-db', label: 'Payment Database', type: 'database', severity: 'CRITICAL', x: 580, y: 240, environment: 'production', owner: 'Finance', description: 'Tier-1 payment data store, CVSS 10.0 SQL injection finding, WAF absent.' },
      { id: 'customer-data', label: 'Customer Data', type: 'data', severity: 'CRITICAL', x: 760, y: 160, environment: 'production', description: 'PII and payment records for 4.2M NovaPay customers.' },
    ],
    edges: [
      { id: 'e1', source: 'internet', target: 'public-api' },
      { id: 'e2', source: 'internet', target: 'auth-api', risky: true, label: 'Internet-exposed' },
      { id: 'e3', source: 'auth-api', target: 'iam-role', risky: true, label: 'Auth bypass' },
      { id: 'e4', source: 'iam-role', target: 'payment-service', risky: true, label: 'Over-privileged assume-role' },
      { id: 'e5', source: 'public-api', target: 'payment-service' },
      { id: 'e6', source: 'payment-service', target: 'payment-db', risky: true, label: 'SQL injection' },
      { id: 'e7', source: 'payment-db', target: 'customer-data', risky: true, label: 'Unencrypted export' },
    ],
  },
  {
    id: 'ap-ci-cd',
    title: 'CI/CD Runner → Cloud Credentials → Production Kubernetes Cluster',
    severity: 'HIGH',
    nodes: [
      { id: 'runner', label: 'CI/CD Runner', type: 'compute', severity: 'HIGH', x: 80, y: 160, owner: 'Platform Infra', description: 'Shared GitLab runner with long-lived AWS credentials.' },
      { id: 'secret', label: 'Exposed Secret', type: 'vulnerability', severity: 'CRITICAL', x: 260, y: 80, description: 'AWS secret access key committed to infra-production repository.' },
      { id: 'iam-user', label: 'Cloud IAM User', type: 'identity', severity: 'HIGH', x: 260, y: 240, owner: 'Platform Infra' },
      { id: 'k8s', label: 'Production Kubernetes Cluster', type: 'compute', severity: 'CRITICAL', x: 460, y: 160, environment: 'production', owner: 'Platform Infra', description: 'Cluster-admin role reachable from the compromised IAM user.' },
      { id: 'secrets-store', label: 'Secrets Store', type: 'storage', severity: 'HIGH', x: 640, y: 160, description: 'Kubernetes secrets containing downstream service credentials.' },
    ],
    edges: [
      { id: 'e1', source: 'runner', target: 'secret', risky: true, label: 'Hardcoded credential' },
      { id: 'e2', source: 'runner', target: 'iam-user' },
      { id: 'e3', source: 'secret', target: 'iam-user', risky: true, label: 'Credential reuse' },
      { id: 'e4', source: 'iam-user', target: 'k8s', risky: true, label: 'cluster-admin bound' },
      { id: 'e5', source: 'k8s', target: 'secrets-store', risky: true, label: 'Full secrets read access' },
    ],
  },
];

export const REMEDIATION_SCENARIOS: RemediationScenario[] = [
  {
    id: 'rem-001',
    title: 'Fix exposed privileged container sb-nginx',
    finding: 'Publicly exposed and highly privileged container using an image with critical exploitable vulnerabilities',
    affectedResource: 'codesmiths.azurecr.io/sb-nginx@sha256:3a12c',
    recommendedFix: 'Upgrade the requests package to version 2.32.0 and remove privileged container flag',
    priority: 'CRITICAL',
    estimatedEffort: '2 hours',
    riskReductionInr: 4200000,
    owner: { name: 'Rahul Verma', initials: 'RV', team: 'Platform Infra' },
    status: 'NOT_STARTED',
    repository: 'codesmiths/ml-kit',
    branch: 'master',
  },
  {
    id: 'rem-002',
    title: 'Enable MFA on privileged accounts',
    finding: '12 privileged accounts without multi-factor authentication',
    affectedResource: 'Okta — NovaPay Production Tenant',
    recommendedFix: 'Enforce MFA policy on all privileged and admin roles across IAM',
    priority: 'HIGH',
    estimatedEffort: '1 day',
    riskReductionInr: 4860000,
    owner: { name: 'Sara Kapoor', initials: 'SK', team: 'Identity' },
    status: 'IN_PROGRESS',
  },
  {
    id: 'rem-003',
    title: 'Patch CVE-2024-21887 on Authentication API',
    finding: 'Remote code execution vulnerability actively exploited in the wild',
    affectedResource: 'Authentication API — production',
    recommendedFix: 'Apply vendor security patch and rotate all associated session tokens',
    priority: 'CRITICAL',
    estimatedEffort: '4 hours',
    riskReductionInr: 3100000,
    owner: { name: 'Arjun Mehta', initials: 'AM', team: 'Payments' },
    status: 'PR_OPENED',
    repository: 'codesmiths/auth-service',
    branch: 'main',
  },
  {
    id: 'rem-004',
    title: 'Rotate leaked AWS secret access key',
    finding: 'AWS secret access key committed to infra-production repository history',
    affectedResource: 'codesmiths/infra-production',
    recommendedFix: 'Revoke the exposed key, rotate credentials, and add pre-commit secret scanning',
    priority: 'CRITICAL',
    estimatedEffort: '3 hours',
    riskReductionInr: 2650000,
    owner: { name: 'Rahul Verma', initials: 'RV', team: 'Platform Infra' },
    status: 'NOT_STARTED',
    repository: 'codesmiths/infra-production',
    branch: 'main',
  },
  {
    id: 'rem-005',
    title: 'Add network segmentation between DB and internal segments',
    finding: 'Flat network topology allows lateral movement from HR Portal to Payment Database',
    affectedResource: 'Production VPC — novapay-prod',
    recommendedFix: 'Introduce security groups and NACLs isolating the payments subnet',
    priority: 'HIGH',
    estimatedEffort: '2 weeks',
    riskReductionInr: 3870000,
    owner: { name: 'Rahul Verma', initials: 'RV', team: 'Platform Infra' },
    status: 'NOT_STARTED',
  },
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  { id: 't1', timestamp: '2026-08-24T06:45:00Z', label: 'Scheduled SAST scan completed', kind: 'success' },
  { id: 't2', timestamp: '2026-08-24T07:55:00Z', label: 'AWS inventory sync completed — 312 resources', kind: 'success' },
  { id: 't3', timestamp: '2026-08-24T08:10:00Z', label: 'GitLab CI/CD scan completed for payments-service', kind: 'success' },
  { id: 't4', timestamp: '2026-08-24T09:10:00Z', label: 'New bug bounty finding received from HackerOne', kind: 'warning' },
  { id: 't5', timestamp: '2026-08-24T09:40:00Z', label: 'GitHub repository sync completed — 5 repositories', kind: 'info' },
];

export const MULTI_SERIES_TREND = [
  { month: 'Mar', enterpriseRisk: 52, criticalFindings: 5, exposedAssets: 9, remediationProgress: 22 },
  { month: 'Apr', enterpriseRisk: 61, criticalFindings: 6, exposedAssets: 10, remediationProgress: 28 },
  { month: 'May', enterpriseRisk: 67, criticalFindings: 7, exposedAssets: 11, remediationProgress: 35 },
  { month: 'Jun', enterpriseRisk: 71, criticalFindings: 8, exposedAssets: 12, remediationProgress: 41 },
  { month: 'Jul', enterpriseRisk: 74, criticalFindings: 8, exposedAssets: 13, remediationProgress: 49 },
  { month: 'Aug', enterpriseRisk: 78, criticalFindings: 9, exposedAssets: 14, remediationProgress: 54 },
];

export const INITIAL_PIPELINE: PipelineStage[] = [
  { id: 'sources', label: 'Sources', state: 'completed', itemCount: 13, lastExecution: '2026-08-24T09:40:00Z', durationMs: 1200 },
  { id: 'ingestion', label: 'Ingestion', state: 'completed', itemCount: 458, lastExecution: '2026-08-24T09:40:12Z', durationMs: 3400 },
  { id: 'normalization', label: 'Normalization', state: 'completed', itemCount: 458, lastExecution: '2026-08-24T09:40:16Z', durationMs: 1800 },
  { id: 'correlation', label: 'Correlation', state: 'completed', itemCount: 18, lastExecution: '2026-08-24T09:40:20Z', durationMs: 2600 },
  { id: 'risk-engine', label: 'Risk Engine', state: 'completed', itemCount: 12, lastExecution: '2026-08-24T09:40:24Z', durationMs: 2100 },
  { id: 'ai-analysis', label: 'AI Analysis', state: 'completed', itemCount: 12, lastExecution: '2026-08-24T09:40:29Z', durationMs: 3100 },
  { id: 'prioritization', label: 'Prioritization', state: 'completed', itemCount: 12, lastExecution: '2026-08-24T09:40:32Z', durationMs: 900 },
  { id: 'remediation', label: 'Remediation', state: 'idle', itemCount: 5 },
];
