// Mock data fallback — used whenever the backend API is unreachable or returns null.
// Keeps the demo fully functional offline.

export const MOCK_ENTERPRISE = {
  enterprise_risk_score: 78,
  total_eal_inr: 84000000,
  total_eal_lakh: 84.0,
  var_95_inr: 268800000,
  current_spend_inr: 2800000,
  top_risk: {
    asset_name: 'Authentication API',
    eal_lakh: 79.8,
    risk_score: 87,
    control_effectiveness_pct: 58,
  },
};

export const MOCK_RISKS = [
  {
    asset_id: 'A003',
    asset_name: 'Authentication API',
    business_service: 'Digital Payments',
    business_criticality: 96,
    eal_inr: 7980000,
    eal_lakh: 79.8,
    risk_score: 87,
    likelihood: 0.21,
    control_effectiveness_pct: 58,
    sources: ['BUG_BOUNTY', 'VULNERABILITY_SCANNER', 'XDR', 'IAM'],
    confidence_pct: 94,
    loss_breakdown: {
      downtime_loss: 1400000,
      ir_cost: 300000,
      recovery_cost: 350000,
      data_breach_cost: 800000,
      regulatory_cost: 450000,
      reputation_cost: 500000,
      total_inr: 3800000,
    },
    risk_drivers: [
      { factor: 'Internet-facing asset', points: 20, direction: 'up' },
      { factor: 'Critical business service', points: 18, direction: 'up' },
      { factor: 'Validated bug bounty finding', points: 17, direction: 'up' },
      { factor: 'Weak MFA (58% coverage)', points: 12, direction: 'up' },
      { factor: 'Full EDR coverage', points: -8, direction: 'down' },
    ],
  },
  {
    asset_id: 'A002',
    asset_name: 'Payment Database',
    business_service: 'Digital Payments',
    business_criticality: 94,
    eal_inr: 6200000,
    eal_lakh: 62.0,
    risk_score: 81,
    likelihood: 0.18,
    control_effectiveness_pct: 67,
    sources: ['VULNERABILITY_SCANNER', 'XDR', 'THREAT_INTEL'],
    confidence_pct: 88,
    loss_breakdown: {
      downtime_loss: 1200000,
      ir_cost: 280000,
      recovery_cost: 300000,
      data_breach_cost: 750000,
      regulatory_cost: 420000,
      reputation_cost: 450000,
      total_inr: 3400000,
    },
    risk_drivers: [
      { factor: 'CVSS 10.0 — SQL Injection', points: 22, direction: 'up' },
      { factor: 'Exploited in wild', points: 18, direction: 'up' },
      { factor: 'Payment data (Tier 1)', points: 15, direction: 'up' },
      { factor: 'Ransomware threat actor active', points: 12, direction: 'up' },
      { factor: 'WAF absent', points: 10, direction: 'up' },
    ],
  },
  {
    asset_id: 'A004',
    asset_name: 'Customer Portal',
    business_service: 'Customer Onboarding',
    business_criticality: 72,
    eal_inr: 3100000,
    eal_lakh: 31.0,
    risk_score: 64,
    likelihood: 0.14,
    control_effectiveness_pct: 74,
    sources: ['BUG_BOUNTY', 'IAM'],
    confidence_pct: 80,
    loss_breakdown: {
      downtime_loss: 600000,
      ir_cost: 200000,
      recovery_cost: 180000,
      data_breach_cost: 420000,
      regulatory_cost: 200000,
      reputation_cost: 300000,
      total_inr: 1900000,
    },
    risk_drivers: [
      { factor: 'IDOR — user data exposure', points: 16, direction: 'up' },
      { factor: 'Internet-facing', points: 14, direction: 'up' },
      { factor: 'Good WAF coverage', points: -7, direction: 'down' },
    ],
  },
  {
    asset_id: 'A005',
    asset_name: 'HR Portal',
    business_service: 'Internal HR',
    business_criticality: 28,
    eal_inr: 850000,
    eal_lakh: 8.5,
    risk_score: 42,
    likelihood: 0.1,
    control_effectiveness_pct: 55,
    sources: ['IAM'],
    confidence_pct: 65,
    loss_breakdown: {
      downtime_loss: 100000,
      ir_cost: 80000,
      recovery_cost: 70000,
      data_breach_cost: 0,
      regulatory_cost: 0,
      reputation_cost: 80000,
      total_inr: 330000,
    },
    risk_drivers: [
      { factor: 'Low MFA coverage', points: 12, direction: 'up' },
      { factor: 'Internal only — not internet-facing', points: -15, direction: 'down' },
    ],
  },
  {
    asset_id: 'A006',
    asset_name: 'Test Server',
    business_service: 'Dev/Test',
    business_criticality: 8,
    eal_inr: 30000,
    eal_lakh: 0.3,
    risk_score: 22,
    likelihood: 0.05,
    control_effectiveness_pct: 30,
    sources: ['VULNERABILITY_SCANNER'],
    confidence_pct: 95,
    loss_breakdown: {
      downtime_loss: 10000,
      ir_cost: 10000,
      recovery_cost: 5000,
      data_breach_cost: 0,
      regulatory_cost: 0,
      reputation_cost: 5000,
      total_inr: 30000,
    },
    risk_drivers: [
      { factor: 'CVSS 9.8 — but isolated', points: 5, direction: 'up' },
      { factor: 'No revenue dependency', points: -20, direction: 'down' },
      { factor: 'Not regulated', points: -12, direction: 'down' },
    ],
  },
];

export const MOCK_SOURCES = [
  { source: 'BUG_BOUNTY', count: 3, status: 'connected' },
  { source: 'VULNERABILITY_SCANNER', count: 3, status: 'connected' },
  { source: 'XDR', count: 2, status: 'connected' },
  { source: 'IAM', count: 2, status: 'connected' },
  { source: 'THREAT_INTEL', count: 2, status: 'connected' },
  { source: 'SIEM', count: 0, status: 'disconnected' },
  { source: 'EDR', count: 0, status: 'disconnected' },
  { source: 'CSPM', count: 0, status: 'disconnected' },
];

export const MOCK_COMPLIANCE = [
  { framework: 'ISO_27001', score: 76 },
  { framework: 'NIST_CSF', score: 82 },
  { framework: 'CIS_CONTROLS', score: 85 },
  { framework: 'RBI_CSF', score: 72 },
  { framework: 'SEBI_CSCRF', score: 81 },
];

export const MOCK_GAPS = [
  {
    framework: 'RBI_CSF',
    control: 'Multi-Factor Authentication',
    gap_description: 'MFA not enforced on all privileged accounts',
    financial_impact_inr: 4860000,
    priority: 'CRITICAL',
  },
  {
    framework: 'ISO_27001',
    control: 'Network Segmentation',
    gap_description: 'Flat network allows lateral movement between DB and internal segments',
    financial_impact_inr: 3870000,
    priority: 'HIGH',
  },
  {
    framework: 'NIST_CSF',
    control: 'Vulnerability Management / Patching',
    gap_description: 'Critical CVE-2024-21887 unpatched for 20+ days',
    financial_impact_inr: 3100000,
    priority: 'HIGH',
  },
];

export const MOCK_TREND = [
  { month: 'Mar', eal: 52 },
  { month: 'Apr', eal: 61 },
  { month: 'May', eal: 67 },
  { month: 'Jun', eal: 71 },
  { month: 'Jul', eal: 79 },
  { month: 'Aug', eal: 84 },
];

export const MOCK_FORECAST = [
  { day: 0, current: 84, withActions: 84 },
  { day: 15, current: 90, withActions: 68 },
  { day: 30, current: 96, withActions: 55 },
  { day: 45, current: 101, withActions: 45 },
  { day: 60, current: 106, withActions: 38 },
  { day: 75, current: 110, withActions: 34 },
  { day: 90, current: 113, withActions: 32 },
];

export const MOCK_FINDINGS = [
  {
    finding_id: 'BB001',
    source_type: 'BUG_BOUNTY',
    source_name: 'HackerOne',
    asset_id: 'A003',
    finding_type: 'AUTH_BYPASS',
    title: 'Authentication bypass on Payment API',
    severity: 'CRITICAL',
    confidence: 0.95,
    first_seen: '2026-08-10',
    status: 'VALIDATED',
  },
  {
    finding_id: 'BB002',
    source_type: 'BUG_BOUNTY',
    source_name: 'HackerOne',
    asset_id: 'A004',
    finding_type: 'IDOR',
    title: 'IDOR allows accessing other users account data',
    severity: 'HIGH',
    confidence: 0.88,
    first_seen: '2026-08-12',
    status: 'VALIDATED',
  },
  {
    finding_id: 'VS001',
    source_type: 'VULNERABILITY_SCANNER',
    source_name: 'Nessus',
    asset_id: 'A003',
    finding_type: 'CVE',
    title: 'CVE-2024-21887 Remote Code Execution',
    cve: 'CVE-2024-21887',
    severity: 'CRITICAL',
    confidence: 0.9,
    first_seen: '2026-08-01',
    status: 'OPEN',
  },
  {
    finding_id: 'VS002',
    source_type: 'VULNERABILITY_SCANNER',
    source_name: 'Nessus',
    asset_id: 'A002',
    finding_type: 'CVE',
    title: 'CVE-2024-3400 SQL Injection',
    cve: 'CVE-2024-3400',
    severity: 'CRITICAL',
    confidence: 0.95,
    first_seen: '2026-08-05',
    status: 'OPEN',
  },
  {
    finding_id: 'VS003',
    source_type: 'VULNERABILITY_SCANNER',
    source_name: 'Nessus',
    asset_id: 'A006',
    finding_type: 'CVE',
    title: 'CVE-2023-44487 HTTP/2 Rapid Reset (Test env)',
    cve: 'CVE-2023-44487',
    severity: 'CRITICAL',
    confidence: 0.95,
    first_seen: '2026-05-01',
    status: 'OPEN',
  },
  {
    finding_id: 'XDR001',
    source_type: 'XDR',
    source_name: 'CrowdStrike Falcon',
    asset_id: 'A003',
    finding_type: 'SUSPICIOUS_AUTH',
    title: '347 failed auth → successful from new IP',
    severity: 'HIGH',
    confidence: 0.82,
    first_seen: '2026-08-18',
    status: 'OPEN',
  },
  {
    finding_id: 'XDR002',
    source_type: 'XDR',
    source_name: 'CrowdStrike Falcon',
    asset_id: 'A002',
    finding_type: 'LATERAL_MOVEMENT',
    title: 'Unusual internal traffic DB → HR server',
    severity: 'HIGH',
    confidence: 0.75,
    first_seen: '2026-08-19',
    status: 'OPEN',
  },
  {
    finding_id: 'IAM001',
    source_type: 'IAM',
    source_name: 'Okta',
    asset_id: 'A003',
    finding_type: 'MFA_GAP',
    title: '12 privileged accounts without MFA',
    severity: 'HIGH',
    confidence: 1.0,
    first_seen: '2026-08-01',
    status: 'OPEN',
  },
  {
    finding_id: 'IAM002',
    source_type: 'IAM',
    source_name: 'Okta',
    asset_id: 'A001',
    finding_type: 'OVER_PRIVILEGE',
    title: '8 service accounts with admin rights',
    severity: 'MEDIUM',
    confidence: 1.0,
    first_seen: '2026-08-01',
    status: 'OPEN',
  },
  {
    finding_id: 'TI001',
    source_type: 'THREAT_INTEL',
    source_name: 'MISP',
    asset_id: 'A003',
    finding_type: 'ACTIVE_EXPLOITATION',
    title: 'CVE-2024-21887 actively exploited by APT groups',
    severity: 'CRITICAL',
    confidence: 0.88,
    first_seen: '2026-08-08',
    status: 'OPEN',
  },
  {
    finding_id: 'TI002',
    source_type: 'THREAT_INTEL',
    source_name: 'MISP',
    asset_id: 'A002',
    finding_type: 'THREAT_ACTOR',
    title: 'Ransomware group targeting payment DBs in APAC',
    severity: 'HIGH',
    confidence: 0.7,
    first_seen: '2026-08-14',
    status: 'OPEN',
  },
  {
    finding_id: 'IAM003',
    source_type: 'IAM',
    source_name: 'Okta',
    asset_id: 'A005',
    finding_type: 'MFA_GAP',
    title: 'HR Portal admins lack MFA enforcement',
    severity: 'MEDIUM',
    confidence: 0.9,
    first_seen: '2026-08-02',
    status: 'TRIAGED',
  },
];

export const MOCK_ASSETS = [
  {
    asset_id: 'A001',
    name: 'Payment Gateway',
    type: 'api_gateway',
    business_unit: 'Finance',
    business_service: 'Digital Payments',
    criticality: 5,
    data_sensitivity: 5,
    revenue_dependency: 5,
    internet_facing: true,
    is_regulated: true,
    value_inr: 50000000,
    business_criticality: 97,
    control_effectiveness: 72,
    controls: { mfa_pct: 80, edr_pct: 95, waf: true, patching_pct: 88, segmentation: true },
  },
  {
    asset_id: 'A002',
    name: 'Payment Database',
    type: 'database',
    business_unit: 'Finance',
    business_service: 'Digital Payments',
    criticality: 5,
    data_sensitivity: 5,
    revenue_dependency: 5,
    internet_facing: false,
    is_regulated: true,
    value_inr: 30000000,
    business_criticality: 94,
    control_effectiveness: 67,
    controls: { mfa_pct: 70, edr_pct: 90, waf: false, patching_pct: 65, segmentation: true },
  },
  {
    asset_id: 'A003',
    name: 'Authentication API',
    type: 'api_gateway',
    business_unit: 'Engineering',
    business_service: 'Digital Payments',
    criticality: 5,
    data_sensitivity: 4,
    revenue_dependency: 5,
    internet_facing: true,
    is_regulated: true,
    value_inr: 20000000,
    business_criticality: 96,
    control_effectiveness: 58,
    controls: { mfa_pct: 58, edr_pct: 100, waf: false, patching_pct: 60, segmentation: false },
  },
  {
    asset_id: 'A004',
    name: 'Customer Portal',
    type: 'web_app',
    business_unit: 'Product',
    business_service: 'Customer Onboarding',
    criticality: 4,
    data_sensitivity: 4,
    revenue_dependency: 3,
    internet_facing: true,
    is_regulated: true,
    value_inr: 10000000,
    business_criticality: 72,
    control_effectiveness: 74,
    controls: { mfa_pct: 75, edr_pct: 80, waf: true, patching_pct: 82, segmentation: false },
  },
  {
    asset_id: 'A005',
    name: 'HR Portal',
    type: 'web_app',
    business_unit: 'HR',
    business_service: 'Internal HR',
    criticality: 2,
    data_sensitivity: 3,
    revenue_dependency: 1,
    internet_facing: false,
    is_regulated: false,
    value_inr: 2000000,
    business_criticality: 28,
    control_effectiveness: 55,
    controls: { mfa_pct: 40, edr_pct: 60, waf: false, patching_pct: 70, segmentation: true },
  },
  {
    asset_id: 'A006',
    name: 'Test Server',
    type: 'server',
    business_unit: 'Engineering',
    business_service: 'Dev/Test',
    criticality: 1,
    data_sensitivity: 1,
    revenue_dependency: 0,
    internet_facing: false,
    is_regulated: false,
    value_inr: 500000,
    business_criticality: 8,
    control_effectiveness: 30,
    controls: { mfa_pct: 20, edr_pct: 30, waf: false, patching_pct: 40, segmentation: true },
  },
];

export const MOCK_ACTIONS = [
  {
    name: 'Enable MFA everywhere',
    cost_inr: 1500000,
    savings_inr: 4860000,
    rosi_pct: 224,
  },
  {
    name: 'Emergency patching (CVE-2024-21887)',
    cost_inr: 1200000,
    savings_inr: 3100000,
    rosi_pct: 158,
  },
  {
    name: 'Network segmentation',
    cost_inr: 3000000,
    savings_inr: 3870000,
    rosi_pct: 29,
  },
];

export const MOCK_CONTROLS = [
  { name: 'Enable MFA everywhere', cost_inr: 1500000, risk_reduction_inr: 4860000, complexity: 'LOW', weeks: 2 },
  { name: 'Emergency patching (CVE-2024-21887)', cost_inr: 1200000, risk_reduction_inr: 3100000, complexity: 'LOW', weeks: 1 },
  { name: 'Network segmentation', cost_inr: 3000000, risk_reduction_inr: 3870000, complexity: 'HIGH', weeks: 8 },
  { name: 'WAF deployment', cost_inr: 900000, risk_reduction_inr: 2100000, complexity: 'MEDIUM', weeks: 3 },
  { name: 'EDR full rollout', cost_inr: 2000000, risk_reduction_inr: 1800000, complexity: 'MEDIUM', weeks: 4 },
  { name: 'SIEM integration', cost_inr: 4500000, risk_reduction_inr: 1500000, complexity: 'HIGH', weeks: 10 },
  { name: 'Security awareness training', cost_inr: 300000, risk_reduction_inr: 500000, complexity: 'LOW', weeks: 1 },
];

export const MOCK_OPTIMIZE_RESULT = {
  budget_inr: 10000000,
  selected_controls: [
    { name: 'Enable MFA everywhere', cost_inr: 1500000, risk_reduction_inr: 4860000, complexity: 'LOW', weeks: 2 },
    { name: 'Emergency patching (CVE-2024-21887)', cost_inr: 1200000, risk_reduction_inr: 3100000, complexity: 'LOW', weeks: 1 },
    { name: 'Network segmentation', cost_inr: 3000000, risk_reduction_inr: 3870000, complexity: 'HIGH', weeks: 8 },
    { name: 'WAF deployment', cost_inr: 900000, risk_reduction_inr: 2100000, complexity: 'MEDIUM', weeks: 3 },
    { name: 'EDR full rollout', cost_inr: 2000000, risk_reduction_inr: 1800000, complexity: 'MEDIUM', weeks: 4 },
  ],
  total_spend_inr: 8600000,
  total_risk_reduction_inr: 16130000,
  rosi_pct: 620,
  unused_budget_inr: 1400000,
};
